config/routes.rb
Rails.application.routes.draw do
  root :to => "pets#index"
  resources :pets do
    resources :medical_records
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/medical_record.rb
class MedicalRecord < ApplicationRecord
  belongs_to :pet

  validates :symptoms, presence: true
  validates :treatment, presence: true

  def csv_colums_values
    [id, pet.name, pet.breed, pet.type_of_animal, symptoms, treatment]
  end

end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  has_many :medical_records, dependent: :destroy
  enum type_of_animal: { dog: 0, cat: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/medical_records_controller.rb
class MedicalRecordsController < ApplicationController
  before_action :set_pet
  before_action :set_medical_record, only: [:show, :edit, :update, :destroy]
  

  # GET /medical_records
  # GET /medical_records.json
  def index
    @medical_records = @pet.medical_records
  end

  # GET /medical_records/1
  # GET /medical_records/1.json
  def show
  end

  # GET /medical_records/new
  def new
    @medical_record = @pet.medical_records.build
  end

  # GET /medical_records/1/edit
  def edit
  end

  # POST /medical_records
  # POST /medical_records.json
  def create
    @medical_record = @pet.medical_records.build(medical_record_params)

    respond_to do |format|
      if @medical_record.save
        format.html { redirect_to pet_medical_records_path(@pet), notice: 'Medical record was successfully created.' }
        format.json { render :show, status: :created, location: @medical_record }
      else
        format.html { render :new }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_records/1
  # PATCH/PUT /medical_records/1.json
  def update
    respond_to do |format|
      if @medical_record.update(medical_record_params)
        format.html { redirect_to pet_medical_record_path(@pet), notice: 'Medical record was successfully updated.' }
        format.json { render :show, status: :ok, location: @medical_record }
      else
        format.html { render :edit }
        format.json { render json: @medical_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_records/1
  # DELETE /medical_records/1.json
  def destroy
    @medical_record.destroy
    respond_to do |format|
      format.html { redirect_to pet_medical_records_path(@pet), notice: 'Medical record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:pet_id])
    end

    def set_medical_record
      @medical_record = @pet.medical_records.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medical_record_params
      params.require(:medical_record).permit(:pet_id, :symptoms, :treatment)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.paginate(page: params[:page], per_page: 8)
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pet_params
      params.require(:pet).permit(:name, :date_of_birth, :breed, :type_of_animal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medical_records_helper.rb
module MedicalRecordsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petcare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/medical_records/_form.html.erb
<%= bootstrap_form_with(model: [@pet, medical_record], local: true) do |form| %>
  <% if medical_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medical_record.errors.count, "error") %> prohibited this medical_record from being saved:</h2>

      <ul>
      <% medical_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_area :symptoms, label: 'Sintomas' %>
  <%= form.text_area :treatment, label: 'Tratamento' %>
 
  <%= form.form_group do %>
    <%= form.submit "Submeter", class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/medical_records/edit.html.erb
<h1>Edição de Prontuário</h1>

<%= render 'form', medical_record: @medical_record %>

<%= link_to 'Back', pet_medical_records_path(@pet), class: "btn btn-info" %>

app/views/medical_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prontuários de <%= @pet.name %></h1>

<table class="table table-borderless table-hover">
  <thead>
    <tr>
      <th>Sintomas</th>
      <th>Tratamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_records.each do |medical_record| %>
      <tr>
        <td><%= medical_record.symptoms %></td>
        <td><%= medical_record.treatment %></td>
        <td><%= link_to 'Editar', edit_pet_medical_record_path(@pet, medical_record), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Apagar', [@pet, medical_record], method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Prontuário', new_pet_medical_record_path, class: 'btn btn-success' %>
<%= link_to 'Voltar para pets', pets_path, class: "btn btn-info" %>

app/views/medical_records/new.html.erb
<div class="container text-center">

<h1>Novo prontuário</h1>

<%= render 'form', medical_record: @medical_record %>

<%= link_to 'Back', pet_medical_records_path(@pet), class: "btn btn-info" %>

</div>

app/views/medical_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet:</strong>
  <%= @medical_record.pet.name %>
</p>

<p>
  <strong>Sintomas:</strong>
  <%= @medical_record.symptoms %>
</p>

<p>
  <strong>Tratamento:</strong>
  <%= @medical_record.treatment %>
</p>

<%= link_to 'Editar', edit_pet_medical_record_path(@pet, @medical_record), class: 'btn btn-warning' %> |
<%= link_to 'Voltar', pet_medical_records_path(@pet), class: 'btn btn-primary' %>

app/views/pets/_form.html.erb
<%= bootstrap_form_with(model: pet, local: true, control_col: "col-sm-4") do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.text_field :name, label: 'Nome' %>
  <%= form.date_field :date_of_birth, label: 'Data de Nascimento' %>
  <%= form.text_field :breed, label: 'Raça' %>
  <%= form.select :type_of_animal, Pet.type_of_animals.keys, label: 'Tipo de animal'%>
  <%= form.form_group do %>
    <%= form.submit "Submeter", class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/pets/edit.html.erb
<div class="container text-center">
  <h1>Alterar informações do Pet</h1>

  <%= render 'form', pet: @pet %>

  <%= link_to 'Voltar', pets_path, class: "btn btn-info" %>
<div>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pets</h1>

<table class="table table-borderless table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data de nascimento</th>
      <th>Raça</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.date_of_birth&.to_date %></td>
        <td><%= pet.breed %></td>
        <td><%= pet.type_of_animal %></td>
        <td><%= link_to 'Prontuários', pet_medical_records_path(pet), class: "btn btn-primary" %></td>
        <td><%= link_to 'Editar', edit_pet_path(pet), class: "btn btn-warning"  %></td>
        <td><%= link_to 'Apagar', pet, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="container text-center">
  <%= link_to 'Adicionar pet', new_pet_path, class: "btn btn-success" %>
</div>
<br>
<div class="container pagination justify-content-center" >
  <%= will_paginate @pets %>
</div>

app/views/pets/new.html.erb
<div class="container text-center">

<h1>Novo Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Voltar', pets_path, class: "btn btn-info" %>
<div>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Data de Nascimento:</strong>
  <%= @pet.date_of_birth&.to_date %>
</p>

<p>
  <strong>Raça:</strong>
  <%= @pet.breed %>
</p>

<p>
  <strong>Tipo de animal:</strong>
  <%= @pet.type_of_animal %>
</p>

<%= link_to 'Editar', edit_pet_path(@pet), class: 'btn btn-warning' %> 
<%= link_to 'Adicionar prontuário', pet_medical_records_path(@pet), class: 'btn btn-success' %>
<%= link_to 'Voltar', pets_path, class: 'btn btn-primary' %>